### PR TITLE
vs2019: Add the preset visual studio project

### PR DESCRIPTION
**Pull request by JSUYA**
This is a compilable vs project to generate library for the fan of visual studio.

Still, there are a lot of compile warnings, it works to generate working dll and lib.

### CODE REVIEW

**Comment by vtorri** [comment]
Hmm, meson can create a VS solution. I use this with meson 0.63.0:

```
rm -rf builddir_vs

meson setup builddir_vs \
      --backend vs \
      --vsenv \
      --prefix=/opt/thor_64 \
      --buildtype=debug \
      --default-library shared \
      -Dvector=true
```

note that --vsenv works correctly with a recent meson.

About __max, what about using [std::max](https://en.cppreference.com/w/cpp/algorithm/max) ?

**Comment by hermet** [comment]
> Hmm, meson can create a VS solution. I use this with meson 0.63.0:
> 
> ```
> rm -rf builddir_vs
> 
> meson setup builddir_vs \
>       --backend vs \
>       --vsenv \
>       --prefix=/opt/thor_64 \
>       --buildtype=debug \
>       --default-library shared \
>       -Dvector=true
> ```
> 
> note that --vsenv works correctly with a recent meson.
> 
> About __max, what about using [std::max](https://en.cppreference.com/w/cpp/algorithm/max) ?

@vtorri Good. tip! and any issues on __max() ?

**Comment by vtorri** [comment]
about __max, no issue afaics. It's just that std::max removes a #ifdef

**Comment by hermet** [comment]
> about __max, no issue afaics. It's just that std::max removes a #ifdef

std::max makes sense to me.

**Comment by JSUYA** [comment]
> Hmm, meson can create a VS solution. I use this with meson 0.63.0:

wow Thank you for good information. I don't think this PR is needed anymore. :)

> About __max, what about using [std::max](https://en.cppreference.com/w/cpp/algorithm/max) ?

I think this should be handled in a new PR, not this pr :)

**Pull request closed without merging**
