### PR TITLE
svg_loader SceneBuilder: Remove incorrect calculation for gradient

### PR DESCRIPTION
**Pull request by JSUYA**
Calculation of objectBoundingBox case in gradient is incorrect code.
This causes the x,y coordinates of the gradient to be calculated incorrectly.
So remove it.

### CODE REVIEW

**Review by hermet — COMMENTED** [review]
@mgrudzinska leave it to your approval.

**Comment by mgrudzinska** [comment]
@JSUYA I would also remove the analogous part of the code for the radial gradient.

could you please tell what was the original purpose of adding this part of the code? 
I thought that maybe it was some kind of optimization, but in such a case we would change the colors together with the bounds of the gradient, so it's not the case.

**Comment by JSUYA** [comment]
> @JSUYA I would also remove the analogous part of the code for the radial gradient.
> 
> could you please tell what was the original purpose of adding this part of the code?
> I thought that maybe it was some kind of optimization, but in such a case we would change the colors together with the bounds of the gradient, so it's not the case.

As you may know, this parsing code is based on efl's svg parser.
The deleted code does not exist linear gradient(in the parser of the efl), but it exists in the radial gradient.
Perhaps it was added incorrectly in the process of implementing.


I checked the history of the code in the radial gradient.
We are doing enough calculations in the parser if the unit is user space.
When I did some tests, this code was calculating the results of cx and cy incorrectly.
So... now I think it's unnecessary.
(But I think there can be side effects or corner cases that I didn't think of...)

I added more patch that remove unnecessary code in radial gradient.
Please cross check these pathces.

**Comment by mgrudzinska** [comment]
@JSUYA I tried to find some cases, in which there would be a problem when we remove this part of the code, but I couldn't find any. I found some cases of radial grad, for which the results are incorrect after this recalculations. 
So I think this part of the code should be removed.

**Review by mgrudzinska — APPROVED** [review]

**Pull request merged**
