### PR TITLE
svg_loader: symbol node without any viewbox/width/height info handled properly

### PR DESCRIPTION
**Pull request by mgrudzinska**
issue #1183

### CODE REVIEW

**Comment by hermet** [comment]
@mgrudzinska It would better to leave you resolve conflicts. It looks screwed up by me. Could you please do that?

**Comment by mgrudzinska** [comment]
@hermet sorry it took so long. rebased. 
I didn't merge it since it wasn't approved

**Review by hermet — APPROVED** [review]

**Comment by hermet** [comment]
@mgrudzinska thanks!

**Comment by hermet** [comment]
@mgrudzinska +If you think it's necessary, you can decide it yourself, See thorvg maintaining domains:
https://github.com/Samsung/thorvg/blob/master/CONTRIBUTING.md

**Pull request merged**
