### PR TITLE
sw_engine: missing implementations added

### PR DESCRIPTION
**Pull request by mgrudzinska**
Rastering functions for masked images that are not rectangular
(clipped) were implemented.

### CODE REVIEW

**Comment by mgrudzinska** [comment]
like #1022 but with the new refactoring - I didn't manage to do this correctly in #1022 :)

**Comment by hermet** [comment]
@mgrudzinska I think you can write more descriptive commit message than "missing implement added"

for example)
Support rendering "translucentImageRleMask", ...

**Comment by mgrudzinska** [comment]
@hermet sorry for that. please check now, would you prefer if I list the functions names in the commit msg?

**Review by hermet — APPROVED** [review]
thanks for your contribution!

**Pull request merged**
