### PR TITLE
svg_loader: preventing cyclic node cloning

### PR DESCRIPTION
**Pull request by mgrudzinska**
If a parent node is a child of the node from which
properties are copied, a cyclic call appears. Fixed

issue #1161

### CODE REVIEW

**Comment by mgrudzinska** [comment]
it's not a global solution, I need to change it

**Comment by mgrudzinska** [comment]
svg with a cycle:
```
<svg height="100" width="100">
  <mask id="d">
  <g>
    <use href="#d"/>
  </g>
  </mask>
  <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
</svg>
```

before this pr caused stackoverflow

**Comment by mgrudzinska** [comment]
> it's not a global solution, I need to change it

now it is

**Comment by hermet** [comment]
@mgrudzinska this is my suggestion: https://github.com/Samsung/thorvg/pull/1168

**Pull request closed without merging**
