### PR TITLE
infra CI: Introduce new build test with github action

### PR DESCRIPTION
**Pull request by JSUYA**
- Description :
This is a build checker using the github action.
When a pull request occurs this action does a basic build,
example build, build with test.

- Screenshot :
image

### CODE REVIEW

**Comment by hermet** [comment]
only 3 lines or introducing something new..

This is a build checker using the github action.
When a pull request occurs this action does a basic build,
example build, build with test.

1. any beneficial point?
 2.  how to manage this build system by others?
For maintenance for the community, you can write a Wiki 
see:  https://github.com/Samsung/thorvg/wiki/Guide-to-ThorVG-Viewer-development-environment

**Comment by JSUYA** [comment]
> only 3 lines or introducing something new..
> 
> This is a build checker using the github action.
> When a pull request occurs this action does a basic build,
> example build, build with test.
> 
> 1. any beneficial point?


1.
In the github action, we can specify a script for several events occurring in github. That script is .github/workflows/actions.yml.

The github action is similar to the existing travis or jenkins.
As thorVG did in travisCI, you can create a docker image, set up the build environment, and test.

We had plans to add unit tests and example builds to the existing travis CI. But to do that, I had to edit the image uploaded on dockerhub. I used dockerhub for quick environment setup and image generation, but github action works faster than that and we can delete build bots that use travis afterwards.

> 2. how to manage this build system by others?
>    For maintenance for the community, you can write a Wiki
>    see:  https://github.com/Samsung/thorvg/wiki/Guide-to-ThorVG-Viewer-development-environment
2.
The wiki and what this bot does is irrelevant.
The example build description is already in the README.
And I think that the unit test description can be done after more test cases are added.

**Comment by JSUYA** [comment]
> 
> > 2. how to manage this build system by others?
> >    For maintenance for the community, you can write a Wiki
> >    see:  https://github.com/Samsung/thorvg/wiki/Guide-to-ThorVG-Viewer-development-environment
> 
> 
> The wiki and what this bot does is irrelevant.
> The example build description is already in the README.
> And I think that the unit test description can be done after more test cases are added.

I have added build management related content to the wiki.
https://github.com/Samsung/thorvg/wiki/ThorVG-build-&-unit-test-CI-management

**Comment by hermet** [comment]
@JSUYA great thanks. Please consider for writing better commit messages.

This is not just bug fix, nor not trivial feature adding...

Like this comment, it must be described fully in commit message:

"In the github action, we can specify a script for several events occurring in github. That script is .github/workflows/actions.yml.

The github action is similar to the existing travis or jenkins.
As thorVG did in travisCI, you can create a docker image, set up the build environment, and test.

We had plans to add unit tests and example builds to the existing travis CI. But to do that, I had to edit the image uploaded on dockerhub. I used dockerhub for quick environment setup and image generation, but github action works faster than that and we can delete build bots that use travis afterwards."

**Pull request merged**
