### PR TITLE
loaders: Consider colorspaces

### LINKED ISSUE #654: Colorspace of the PNG image is not changed in tvg::SwCanvas::ABGR8888
PicturePng.cpp
```diff
diff --git a/src/examples/PicturePng.cpp b/src/examples/PicturePng.cpp
index 9dd6a03..c5decbc 100644
--- a/src/examples/PicturePng.cpp
+++ b/src/examples/PicturePng.cpp
@@ -54,7 +54,7 @@ void tvgSwTest(uint32_t* buffer)
 {
     //Create a Canvas
     swCanvas = tvg::SwCanvas::gen();
-    swCanvas->target(buffer, WIDTH, WIDTH, HEIGHT, tvg::SwCanvas::ARGB8888);
+    swCanvas->target(buffer, WIDTH, WIDTH, HEIGHT, tvg::SwCanvas::ABGR8888);
 
     /* Push the shape into the Canvas drawing list
        When this shape is into the canvas list, the shape could update & prepare
```

If changing the Colorspace, the Red and Blue colors of the image should changed.

expected results
image

### PR DESCRIPTION
**Pull request by mmaciola**
@issue: fixes #654

### CODE REVIEW

**Comment by hermet** [comment]
Important patch. It might be unavoidable, but we need to consider the best approach as possible. let's see...

**Comment by mmaciola** [comment]
Please find changes

**Review by hermet — APPROVED** [review]
@mmaciola good job. thanks.

**Comment by hermet** [comment]
@mmaciola fyi, i had to revert the patch...
https://github.com/Samsung/thorvg/commit/3b2e1f42918cf1c073ababa6c88c5449ca73902b

Need to consider from the base....

**Pull request merged**
