### PR TITLE
infra coding_style: Add coding style check bot

### PR DESCRIPTION
**Pull request by JSUYA**
- Description :

Add a bot that checks the coding style using cpplint
and reports the result as a review comment.

This feature refers to the repository where cpplint
and docker settings with github-action.
This action works whenever a PR is created and updated.

In cpplint, only the violation of ThorVG's coding style is reported
as a warning using several options.
whitespace/parens
whitespace/indent
whitespace/end_of_line
whitespace/blank_line

The bot will review all of the contents of all files in the current commit file list,
However, in the future, we will improve Bot to only review the changes.

- Screen Shots (if any) :
[code change example]
image
[bot's review]
image
[No problem case]
image

### CODE REVIEW

**Comment by hermet** [comment]
@JSUYA  Hmm where is the coding rule specified?

**Comment by JSUYA** [comment]
@hermet 
This is the repo that runs cpplint.
https://github.com/JSUYA/cpp-linter-action

By referring to this repo in the yml file, the script in repo runs to create a Docker image and runs cpplint.
`        uses: jsuya/cpp-linter-action@master`

I think the repo can be moved to the official organization later.

**Comment by JSUYA** [comment]
I updated this script so that it does not have dependencies of external packages.

**Comment by JSUYA** [comment]
I have written a description of this feature in WIKI.
https://github.com/Samsung/thorvg/wiki/Coding-style-check

**Pull request merged**
